apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-provider-integration
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kuroweb/k8s.git
    targetRevision: HEAD
    path: manifests/auth-provider-integration
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-provider-integration
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
