apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kuroweb/k8s.git
    targetRevision: HEAD
    path: manifests/cloudflare-ddns
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-ddns
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
