apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kuroweb/k8s.git
    targetRevision: HEAD
    path: manifests/portainer
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
