apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.16.5
    helm:
      parameters:
        - name: csi.kubeletDirPath
          value: /var/lib/k0s/kubelet
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
