apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-cluster-issuer
spec:
  acme:
    email: kuromitsu0104@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls-cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
