apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: price-monitoring-integration

images:
  - name: docker-registry.kuroweb.net/price-monitoring-backend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-integration
    newTag: 7c6da16f7f63400cd7f7a92c2190056c89acea0d
  - name: docker-registry.kuroweb.net/price-monitoring-backend-playwright:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-backend-playwright-integration
    newTag: 7c6da16f7f63400cd7f7a92c2190056c89acea0d
  - name: docker-registry.kuroweb.net/price-monitoring-frontend:placeholder
    newName: docker-registry.kuroweb.net/price-monitoring-frontend-integration
    newTag: 7c6da16f7f63400cd7f7a92c2190056c89acea0d

patches:
  - path: patch-loadbalancer-ips.yaml
  - path: patch-ingress-cert-host.yaml
  - path: patch-backend-deployment.yaml
  - path: patch-backend-migrate-deployment.yaml
  - path: patch-batch-env.yaml
  - path: patch-frontend-deployment.yaml
  - path: patch-playwright-replicas.yaml
  - path: patch-batch-replicas.yaml
