# Add loadBalancerIP to Services (integration IPs from README)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  loadBalancerIP: 10.15.100.228
---
apiVersion: v1
kind: Service
metadata:
  name: backend-db-service
spec:
  loadBalancerIP: 10.15.100.222
---
apiVersion: v1
kind: Service
metadata:
  name: backend-redis-service
spec:
  loadBalancerIP: 10.15.100.223
---
apiVersion: v1
kind: Service
metadata:
  name: backend-playwright-service
spec:
  loadBalancerIP: 10.15.100.225
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  loadBalancerIP: 10.15.100.227
