apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: auth-provider-integration
spec:
  selector:
    app: auth-provider
    server: backend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  loadBalancerIP: 10.15.100.234

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: auth-provider-integration
  labels:
    app: auth-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-provider
      server: backend
  template:
    metadata:
      labels:
        app: auth-provider
        server: backend
    spec:
      containers:
        - name: backend
          image: docker-registry.kuroweb.net/auth-provider-backend-integration:00d018498bf8ad28dfa7789edebedfc6f924af3a
          command:
            [
              "./bin/rails",
              "server",
              "-b",
              "0.0.0.0",
              "-p",
              "3000",
              "-e",
              "integration",
            ]
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: DB_HOST_NAME
              value: backend-db-service
            - name: DB_DATABASE_NAME
              value: rails
            - name: DB_USER_NAME
              value: root
            - name: DB_PASSWORD
              value: ""
            - name: REDIS_URL
              value: "redis://backend-redis-service:6379"
            - name: ALLOWED_ORIGINS
              value: "10.15.100.234,integration.auth-provider.kuroweb.net,www.integration.auth-provider.kuroweb.net,backend-service"
            - name: DOMAIN_NAME
              value: "integration.auth-provider.kuroweb.net"
            - name: DD_SERVICE
              value: "auth-provider-integration"
            - name: DD_ENV
              value: "integration"
            - name: DD_AGENT_HOST
              value: "datadog-agent.datadog.svc.cluster.local"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: RAILS_MASTER_KEY
            - name: BUGSNAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: BUGSNAG_API_KEY
          volumeMounts:
            - name: op-private-key
              mountPath: /app/certs/private.pem
              subPath: OP_PRIVATE_KEY
              readOnly: true
      volumes:
        - name: op-private-key
          secret:
            secretName: backend-secret
